---
- hosts: webservers
  remote_user: root
  tasks:
  - name: Installing Apache Web server
    yum:
      name: httpd
      state: installed
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
