--- 
- 
  become: true
  hosts: webservers
  name: "nginx install & start service"
  tasks: 
    - 
      name: "install nginx"
      yum: 
        name: nginx
        state: latest
    - 
      name: "start nginx"
      service: 
        name: nginx
        state: started
