--- 
- 
  handlers: 
    - 
      name: "restart apache"
      service: 
        name: httpd
        state: restarted
  hosts: webservers
  remote_user: root
  tasks: 
    - 
      name: "Installing Apache Web server"
      yum: 
        name: httpd
        state: installed
    - 
      name: "ensure apache is at the latest version"
      notify: 
        - "restart apache"
      yum: 
        name: httpd
        state: latest
    - 
      name: "ensure apache is running"
      service: 
        name: httpd
        state: started
  vars: 
    http_port: 80
    max_clients: 200
